version: '3.3'

services:
  medbook-api:
    container_name: medbook-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3004
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks: 
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"
  
  medbook-batch:
    container_name: medbook-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3005
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    networks: 
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"


networks:
  monorepo-network:
    driver: bridge



# medbook-next:    localhost:4000 <=> container:3000
# medbook-api:     localhost:4001 <=> container:3004
# medbook-batc     localhost:4002 <=> container:3005